app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime 


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))



class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True, index = True)
    blogs = db.relationship('Blog',backref = 'user',lazy = "dynamic")
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_hash = db.Column(db.String(255))
    pass_secure = db.Column(db.String(255))
    comments = db.relationship('Comment',backref = 'user',lazy = 'dynamic')

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self,password):
        self.pass_secure = generate_password_hash(password)
    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)


    def __repr__(self):
        return f'User {self.username}'



class Blog(db.Model):
    __tablename__ = 'blogs'
    id = db.Column(db.Integer,primary_key = True)
    title = db.Column(db.String(255))
    blog = db.Column(db.String)
    comments = db.relationship('Comment',backref = 'blog',lazy = 'dynamic')
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    date_of_blog = db.Column(db.DateTime,default=datetime.utcnow)

    def save_blog(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_all_blogs(cls):
        '''
        Function that queries the database and returns all the blogs
        '''

        return Blog.query.all()

    @classmethod
    def get_blogs(cls,id):
        blogs = Blog.query.order_by(blog_id = id).desc.all()
        return blogs
        

    


    def __repr__(self):
        return f'Blog {self.blog}'

class Comment(db.Model):
    all_comments = []
    __tablename__ = 'comments'
    id = db.Column(db.Integer,primary_key = True)
    blog_id = db.Column(db.Integer,db.ForeignKey('blogs.id'))
    description = db.Column(db.Text)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def save_comments(self):
        db.session.add(self)
        db.session.commit()
    def __repe__(self):
        return f"Comment : id {self.id} comment : {self.description}"

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,TextAreaField
from wtforms.validators import Required

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.' ,validators = [Required()])

    submit = SubmitField('Submit')
class BlogForm(FlaskForm):
    title = StringField('title',validators=[Required()])
    blog = TextAreaField('Write your blog here',validators=[Required()])
    submit = SubmitField('Submit')
class CommentForm(FlaskForm):
    description = TextAreaField('Add comment',validators = [Required()])
    Submit = SubmitField('submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
photos = UploadSet('photos',IMAGES)
mail = Mail()


def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

     # configure UploadSet
    configure_uploads(app,photos)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from flask_login import login_required,current_user
from ..models import User,Blog,Comment
from .forms import UpdateProfile,BlogForm,CommentForm
from .. import db,photos




@main.route('/', methods = ['GET','POST'])
def index():
    '''
    View root page function that returns the index page and its data
    '''
    blogs = Blog.get_all_blogs()
    title = 'Personal blog posts'

    return render_template('index.html', title = title, blogs = blogs)



@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)
    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>',methods = ['GET', 'POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort (404)

    form = UpdateProfile()

    if form.validate_on_submite():
        user.bio = form.bio.data 
        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname = user.username))
    return render_template('profile/update.html',form = form)
@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))
@main.route('/blogs/new/',methods = ['GET','POST'])
@login_required
def new_blog():
    form = BlogForm()

    if form.validate_on_submit():
        title = form.title.data
        blog = form.blog.data
        user_id = current_user
        print(current_user._get_current_object().id)
        new_blog = Blog(user_id=current_user._get_current_object().id, title=title,blog=blog)
        db.session.add(new_blog)
        db.session.commit()

        return redirect(url_for('main.index'))
    return render_template('blogs.html',form=form,)

@main.route('/blog/comment/new/<int:blog_id>', methods = ['GET','POST'])
@login_required
def new_comment(blog_id):
    form = CommentForm()
    blog = Blog.query.get(blog_id)
    if form.validate_on_submit():
        description = form.description.data
        new_comment = Comment(description = description, user_id = current_user._get_current_object().id, blog_id = blog_id)
        db.session.add(new_comment)
        db.session.commit()

        return redirect(url_for('.new_comment',blog_id = blog_id))
    all_comments = Comment.query.filter_by(blog_id=blog_id).all()
    return render_template('comments.html',form = form ,comment = all_comments, blog=blog)



    

app/templates/base.html
{% extends 'bootstrap/base.html'%}




<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% if title %}
        <title> {{ title }}</title>
        {% else %}
        <title> Welcome to the best blog website </title>
        {% endif %}
    </head>
    <body>
        <!-- Content block -->

        <!-- Navbar block  --> 
        {% block navbar %}
        {% include 'navbar.html' %}
        {% endblock %}

        {% block content %}

        {% endblock%}
    </body>
</html>

app/templates/blogs.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% import 'macros.html' as macro%}

{% block content%}
<div class="container">
    <div class="row">
        <div class="jumbotron">
            <div class="col-md-8">

                {{wtf.quick_form(form)}}

            </div>
            

        </div>

    </div>

</div>
{% endblock %}

app/templates/comments.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% import 'macros.html' as macro%}



{% block content%}
    <div class='container'>
        <div class="row">
            <div class="panel panel-header">
                <h3>{{blog.title}}</h3>
           
                
                    <h4>{{blog.blog}}</h4>
                </div>

            <div class="panel panel-body">
            <div class="col-md-8">
                {{wtf.quick_form(form)}}
                

            </div>
            <div class="col-md-12">
                <h4>Comments</h4>
                {{macro.displayComment(comment)}}

            </div>
            </div>  

        </div>

    </div>
{% endblock%}

app/templates/index.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}



{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="panel">
        <div class="col-md-12">
                {{macro.display(blogs)}}


        </div>
        
    </div>

</div>
{% endblock %}

app/templates/macros.html
{% macro display(blog_list)%}
<div class= "row">
    {% for blog in blog_list %}
    <div class="col-md-9">
        <div class="panel panel-header"></div>
            <h3 style="text-align: center; font-family: cursive; font-size: 30px;">{{blog.title}}</h3>
            <div class="panel panel-body">
                <h4 style="font-family:  Cambria, Cochin, Georgia, Times, 'Times New Roman', serif; ;font-size: 20px">{{blog.blog}}</h4>

                <footer style="font-family: cursive; font-size: 20px;">Posted by {{blog.user.username}}</footer>
                <a href="{{url_for('main.new_comment', blog_id = blog.id)}}" class="btn btn-primary"> Add a comment </a>


            </div>

        

    </div>
    {% endfor  %}
    


</div>
{% endmacro %}
{% macro displayComment(comments) %}
<ul>

    {% for comment in comments %}
        <div class="row">
                <p>{{ comment.description }}</p>
                <small> posted by {{comment.user.username}}</small>
        </div>
    {% endfor %}


</ul>
{% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{url_for('main.new_blog')}}" style="color:aqua; font-family:Arial, Helvetica, sans-serif;"> Write a BLOG </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/"  style="color:aqua; font-family:Arial, Helvetica, sans-serif;">Home</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{url_for('main.profile',uname=current_user.username)}}"  style="color: beige; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;">Profile</a></li>
                <li style="color:white;padding:15px;">{{current_user.username}}</li>
                <li><a href="{{url_for('auth.logout')}}" style="color: beige; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;">Sign out</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}"  style="color: beige; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;">Sign in</a></li>
                {%endif%}
              </ul>

        </div>

    </div>
</div>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    <div class="col-md-4">
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
    {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

        <input type="file"  name="photo" class="form-control" required>
        <input type="submit">
      </form>
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
    {% endif %}

  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}